services:
  kypidbot:
    image: ghcr.io/jus1d/kypidbot:latest
    build: .
    container_name: kypidbot
    env_file:
      - .env
    environment:
      - DB_PATH=/data/kypidbot.db
    volumes:
      - ./.db:/data
    restart: unless-stopped
