env: "local" # local, dev or prod

bot:
  token: "telegram-token"
  messages_path: "./messages/messages.yaml"

notifications:
  poll_interval: 1s
  date_upcoming_in: 1h
  registration_reminder_in: 24h
  invite_reminder_in: 10m

ollama:
  host: "ollama"
  port: "11434"
  model: "model-name" # ollama pull model-name before

postgres:
  host: "postgres"
  port: "5432"
  user: "kypidbot"
  name: "kypidbot"
  password: "kypidbot"
  sslmode: "disable"

s3:
  host: "minio"
  port: "9000"
  access_key_id: "admin"
  secret_access_key: "minioadmin"
  bucket: "kypidbot-photos"
  region: "us-east-1"
  use_ssl: false
