env: "local" # local, dev or prod

bot:
  token: "telegram-token"
  messages_path: "./messages/messages.yaml"

notifications:
  poll_interval: 1s
  date_upcoming_in: 1h
  registration_reminder_in: 24h
  invite_reminder_in: 10m

gemini:
  api_key: "your-gemini-api-key"
  model: "gemini-embedding-001"

postgres:
  host: "postgres"
  port: "5432"
  user: "kypidbot"
  name: "kypidbot"
  password: "kypidbot"
  sslmode: "disable"
